import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportOptions {
    title: string;
    columns: string[];
    data: string[][];
    filename: string;
    tenantId: string;
    token: string;
}

export const generateReport = async ({ title, columns, data, filename, tenantId, token }: ReportOptions) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // Fetch Tenant Details
    let tenantDetails: { name: string; logo?: string; address?: string; phone?: string; email?: string } | null = null;
    try {
        const response = await fetch(`http://localhost:3001/tenants/${tenantId}`, {
            headers: { Authorization: `Bearer ${token}` }
        });
        if (response.ok) {
            tenantDetails = await response.json();
        }
    } catch (error) {
        console.error('Failed to fetch tenant details for report', error);
    }

    // --- Header ---
    let yPos = 20;

    // Logo
    if (tenantDetails?.logo) {
        try {
            const img = new Image();
            img.src = tenantDetails.logo;
            await new Promise((resolve) => {
                img.onload = resolve;
                img.onerror = resolve; // Continue even if logo fails
            });
            doc.addImage(img, 'PNG', 14, 15, 25, 25);
        } catch (e) {
            console.error("Failed to load logo for PDF", e);
        }
    }

    // Company Info
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(tenantDetails?.name || 'My Restaurant', 45, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);

    let contactY = 28;
    if (tenantDetails?.address) {
        doc.text(tenantDetails.address, 45, contactY);
        contactY += 5;
    }
    if (tenantDetails?.phone) {
        doc.text(`Phone: ${tenantDetails.phone}`, 45, contactY);
        contactY += 5;
    }
    if (tenantDetails?.email) {
        doc.text(`Email: ${tenantDetails.email}`, 45, contactY);
    }

    // Report Title & Date
    doc.setDrawColor(200);
    doc.line(14, 45, pageWidth - 14, 45); // Separator line

    doc.setTextColor(0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${date}`, 14, 62);

    // --- Content ---
    autoTable(doc, {
        startY: 70,
        head: [columns],
        body: data,
        theme: 'striped',
        headStyles: { fillColor: [66, 139, 202] },
        styles: { fontSize: 10 },
    });

    // --- Footer ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by Cloudex POS', pageWidth / 2, pageHeight - 10, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
    }

    doc.save(`${filename}_${new Date().toISOString().split('T')[0]}.pdf`);
};
